<?php
// Database connection settings for the GPGD IT Professional Certification Programme.
// This app connects as a dedicated 'gpgd_app' user scoped only to the
// gpgd_it_program database (not root), generated by setup-mysql.ps1.

return [
    'host'     => getenv('DB_HOST') ?: 'localhost',
    'port'     => getenv('DB_PORT') ?: '3306',
    'database' => getenv('DB_NAME') ?: 'gpgd_it_program',
    'username' => getenv('DB_USER') ?: 'gpgd_app',
    'password' => getenv('DB_PASSWORD') ?: 'tgQ2Vi7RLCPHTKU5e6wkY0Am',
];